baseURL = "https://www.dataspacepublishing.com/"
languageCode = "en-us"
title = "Dataspace Publishing"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  book = "books"
  author = "authors"

[module]
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"
  [[module.imports]]
    path = "github.com/bradp/hugo-feather-icons"
