baseURL = "https://www.dataspacepublishing.com/"
languageCode = "en-us"
title = "Dataspace Publishing"

# Site structure
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  book = "books"
  author = "authors"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weigt = 100
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 120

[Social]
  twitter = "DataspacePub"

[build]
  writeStats = true

# Misc config
googleAnalytics = "UA-xxxxx-1"
pygmentsCodeFences = true
pygmentsUseClasses = true



# MODULAR IMPORTS
# ==============
[module]

# base of virtual union filesystem
[[module.mounts]]
  source = "assets/css"
  target = "assets/css"
[[module.mounts]]
  source = "assets/scss"
  target = "assets/scss"
[[module.mounts]]
  source = "assets/js"
  target = "assets/js"

# Bootstrap from node
[[module.mounts]]
  source = "node_modules/bootstrap/dist/css"
  target = "assets/css"
[[module.mounts]]
  source = "node_modules/bootstrap/scss"
  target = "assets/scss"
[[module.mounts]]
  source = "node_modules/bootstrap/dist/js"
  target = "assets/js"

# jQuery from node
[[module.mounts]]
  source = "node_modules/jquery/dist"
  target = "assets/js"

# Popper.js from node
[[module.mounts]]
  source = "node_modules/popper.js/dist/umd"
  target = "assets/js"
