baseURL = "https://www.dataspacepublishing.com/"
languageCode = "en-us"
title = "Dataspace Publishing"


[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  book = "books"
  author = "authors"

[module]
  # import theme
  [[module.imports]]
    path = "github.com/dataspacepub/spacetime"
