baseURL = "https://www.dataspacepublishing.com/"
languageCode = "en-us"
title = "Dataspace Publishing"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  book = "books"
  author = "authors"
  
